version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./infra/php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    volumes: 
    - ./infra/mariadb/my.cnf:/etc/mysql/my.cnf
    - ./infra/mariadb/data:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MAEIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      TZ: 'Asia/Tokyo'

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
